export default [
  {
    id: 1,
    image: "yoga",
    orderPc: 1,
    orderMobile: 4,
    text: "Relax and rejuvenate with serene yoga sessions amidst nature",
    textMobile: "Relax yoga sessions",
  },
  {
    id: 2,
    image: "biking",
    orderPc: 2,
    orderMobile: 3,
    text: "Embark on thrilling biking adventures",
    textMobile: "Embark on thrilling biking adventures ",
  },
  {
    id: 3,
    image: "boardGames",
    orderPc: 3,
    orderMobile: 5,
    text: "Gather around and enjoy board games and darts",
    textMobile: "Enjoy board games",
  },
  {
    id: 4,
    image: "bbq",
    orderPc: 4,
    orderMobile: 1,
    text: "Delight in sizzling BBQ feasts  under the open sky",
    textMobile: "Delight in sizzling BBQ",
  },
  {
    id: 5,
    image: "nature",
    orderPc: 5,
    orderMobile: 2,
    text: "Indulge in ultimate relaxation, surrounded by nature's tranquility",
    textMobile: "Feel the nature",
  },
];
